### ISSUE TITLE
is this somthing needed to be looked into?

### ISSUE THREAD

**Issue by Shadow322** [s1cp/nxshot#11]
C:\nxshot-master1\nxshot-master>python nxshot.py C:\Nintendo\Album
Organizing screenshots...
Organized 1 of 464 files.
Organized 2 of 464 files.
Organized 3 of 464 files.
Organized 4 of 464 files.
Organized 5 of 464 files.
Organized 6 of 464 files.
Organized 7 of 464 files.
Organized 8 of 464 files.
Organized 9 of 464 files.
Organized 10 of 464 files.
Organized 11 of 464 files.
Organized 12 of 464 files.
Organized 13 of 464 files.
Organized 14 of 464 files.
Organized 15 of 464 files.
Organized 16 of 464 files.
Organized 17 of 464 files.
Organized 18 of 464 files.
Organized 19 of 464 files.
Organized 20 of 464 files.
Organized 21 of 464 files.
Organized 22 of 464 files.
Traceback (most recent call last):
  File "nxshot.py", line 98, in <module>
    checkFolders(screenshotlist)
  File "nxshot.py", line 59, in checkFolders
    int(year),
ValueError: invalid literal for int() with base 10: 'Joy-'

**Comment by Shadow322** [comment]
also only organized one game that is Shovel Knight didn't organize Doom or SMO or any of my other games and i have no "unknown folder"

**Comment by s1cp** [comment]
Do you put any picture that starts with "Joy-" on that album folder? It's not meant to organize pictures that were renamed.

**Comment by Shadow322** [comment]
ok solved that then

Traceback (most recent call last):
  File "nxshot.py", line 98, in <module>
    checkFolders(screenshotlist)
  File "nxshot.py", line 71, in checkFolders
    outputfolder.mkdir(parents=True, exist_ok=True)
  File "C:\Python36-32\lib\pathlib.py", line 1226, in mkdir
    self._accessor.mkdir(self, mode)
  File "C:\Python36-32\lib\pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
NotADirectoryError: [WinError 267] The directory name is invalid: 'c:\\Nintendo\\Album\\Organized\\Oceanhorn: Monster of Uncharted Seas'

**Comment by Shadow322** [comment]
i suggest replacing : with -

**Comment by s1cp** [comment]
Fixed
