### ISSUE TITLE
4E04D8234DC33FAEC8172DB7D0A88D27

### ISSUE THREAD

**Issue by Shadow322** [s1cp/nxshot#15]
dont know its name
![2017112022044800-4e04d8234dc33faec8172db7d0a88d27](https://user-images.githubusercontent.com/15938645/33055152-7c202a98-ce43-11e7-8cac-973008caed81.jpg)

**Comment by s1cp** [comment]
It's すみっコぐらし すみっコパークへようこそ or Sumikko Gurashi: Sumikko Park he Youkoso
