### ISSUE TITLE
Slime-san, Shantae, Wonder Boy, Lego City, Has-Been Heroes, Binding of Isaac, Little Inferno

### ISSUE THREAD

**Issue by JulienPolizzi** [s1cp/nxshot#26]
E769E2D93519E8D860445ED00A4A5E3D Slime-san
65590FD04B4DF51BB1D8C39A50C8376C Shantae - Half-Genie Hero
E2DADADBE272660A316475FCCDECFECB Wonder Boy - The Dragon's Trap
07D9814262B38BD7F7D0D29A25B162B8 LEGO CITY UNDERCOVER
BB278FDC5DD434CF8F30F224CFBF517A Has-Been Heroes
1B7686315C6209EBBD25E3E11E89316C The Binding of Isaac - Afterbirth+
466B5BDBC8CAAC6D679B16794C9D1E3F Little Inferno

**Comment by alademan** [comment]
I'll add these and create a pull request @s1cp
