### ISSUE TITLE
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'

### ISSUE THREAD

**Issue by semicolonsnet** [s1cp/nxshot#28]
Running on macOS 10.13. Get the following error on invoking the script:

> Traceback (most recent call last):
>   File "nxshot.py", line 105, in <module>
>     checkFolders(screenshotlist)
>   File "nxshot.py", line 74, in checkFolders
>     posixtimestamp = time.timestamp()
> AttributeError: 'datetime.datetime' object has no attribute 'timestamp'

**Comment by s1cp** [comment]
Are you using python 3?

**Comment by semicolonsnet** [comment]
Used with Python 3.3, and it worked - thanks! (Should have checked that earlier...)
