### ISSUE TITLE
Determine Title Names Programmatically

### ISSUE THREAD

**Issue by DavidBuchanan314** [s1cp/nxshot#42]
All the ID's in `gameids.json` are actually just the game TitleIDs, encrypted with AES-ECB, with a hardcoded key.

Example code to decrypt:

```python
from Crypto.Cipher import AES

titleid = bytes.fromhex("F1C11A22FAEE3B82F21B330E1B786A39") # BotW
key = bytes.fromhex("CENSORED")

cipher = AES.new(key, AES.MODE_ECB)
decrypted = cipher.decrypt(titleid)

print(decrypted[7::-1].hex())
```

Let me know if you want the key, I'm honestly not sure about the legalities of sharing it, so I understand if you'd rather not have it in your code.

**Comment by DavidBuchanan314** [comment]
Alternatively, I could write a script to parse this: http://switchbrew.org/index.php?title=Title_list/Games

encrypt the IDs, and automatically produce an updated `gameids.json` file.

**Comment by s1cp** [comment]
Thank you so much for the explanation. I had tried to figure out how the IDs were being generated from but had no clue on how it was being done. Could you please tell me the name of the key? I think I have it saved somewhere.

**Comment by s1cp** [comment]
So, I'm trying to implement this code and found the following error while trying to encrypt the IDs:

``ValueError: Data must be aligned to block boundary in ECB mode``

I don't have much experience with crypto so any help would be welcome.

**Comment by DavidBuchanan314** [comment]
@Querschlag https://www.google.com/search?q=%22mysterious+RNG+seeds%22 :wink:

**Comment by 5685C4A059D5** [comment]
> IDK what the name is, but it's at offset 0x71000704D0 if you load the capsrv NSO up in IDA. The sha1 hash is: `23b1daf105047248f2e51375a17cff6d51e01350`
> 
> Edit: You can extract it from the capsrv nso (Dumped with dumpModules.js) like so: `dd if=capsrv/main of=the_key bs=1 skip=260905 count=16`

7 years later I'm here to ask, how exactly do you extract this key with dd?
I tried the provided dd command on several versions of the capsrv nso (the ones in fw 4.0.0, 5.0.0 and 5.1.0) but the output file hash never match the sha1 above.

**Comment by DavidBuchanan314** [comment]
The key was `B7ED7A66C80B4B008BAF7F0589C08224`
