### ISSUE TITLE
Not Sure How to Name These Game IDs

### ISSUE THREAD

**Issue by alademan** [s1cp/nxshot#6]
I've got two Game IDs that are different parts of the OS:

CCFA659F4857F96DDA29AFEDB2E166E6 seems to be the friends/profile interface
1E95E5926F1CB99A87326D927F27B47E may be the controller config interface?

See attached
2017090100325500-CCFA659F4857F96DDA29AFEDB2E166E6.jpg:
![2017090100325500-ccfa659f4857f96dda29afedb2e166e6](https://user-images.githubusercontent.com/187255/33047217-4d4b2ae8-ce1a-11e7-90fa-8497a073f5ad.jpg)

2017090401323800-1E95E5926F1CB99A87326D927F27B47E.jpg:
![2017090401323800-1e95e5926f1cb99a87326d927f27b47e](https://user-images.githubusercontent.com/187255/33047229-514cddbc-ce1a-11e7-9faa-4f7c3e07393a.jpg)

**Comment by s1cp** [comment]
I think "CCFA659F4857F96DDA29AFEDB2E166E6" could be named as "User Page" and "1E95E5926F1CB99A87326D927F27B47E" as "Message Overlay" or "Controller Configuration".

**Comment by s1cp** [comment]
Added.
