### ISSUE TITLE
Does not work at all???

### ISSUE THREAD

**Issue by Shadow322** [s1cp/nxshot#9]
C:\nxshot-master>nxshot.py C:\Nintendo\Album
No folder specified! Exitting...

**Comment by s1cp** [comment]
Try on cmd:
python nxshot.py "C:\Nintendo\Album"

**Comment by Shadow322** [comment]
C:\nxshot-master>nxshot.py "C:\nxshot-master\Album"
No folder specified! Exitting...

**Comment by s1cp** [comment]
Please try it without opening python. Do the command on my previous message.

**Comment by Shadow322** [comment]
i never opend python

**Comment by s1cp** [comment]
Please send a picture of your command prompt.

**Comment by Shadow322** [comment]
![image](https://user-images.githubusercontent.com/15938645/33051825-71933816-ce31-11e7-9cd7-4cbbd5ec380a.png)

**Comment by Shadow322** [comment]
![image](https://user-images.githubusercontent.com/15938645/33051871-a964e01e-ce31-11e7-98a5-ae32a2cc9daf.png)

**Comment by Shadow322** [comment]
![image](https://user-images.githubusercontent.com/15938645/33051911-edb722ae-ce31-11e7-86e3-c51b402d403d.png)

**Comment by s1cp** [comment]
Please, type this command:
``python nxshot.py "C:\Nintendo\Album"``

**Comment by s1cp** [comment]
Ok, try the latest version and tell me if it works now.

**Comment by Shadow322** [comment]
works now whatever u did
